### PR TITLE
[Assembly] Add duplicate label check

### LINKED ISSUE #266: [Assembly] B2R2 Assembler Fails to Detect Duplicate Labels
# PoC
The B2R2 assembler does not properly validate and reject duplicate symbol definitions. This can lead to silent errors and unpredictable behavior in the generated shellcode, as the assembler silently overwrites the address of the first label with the second one.

While it is unclear if this is intentional behavior, I believe the assembler should abort with an error rather than failing silently.
```
act exploit():
    bv shellcode = x86-64 {{
        call label
    label:
        pop rax
        pop rbx
        xor rax, rbx
        add rax, 0x15
        push rax
    label:
        ret
    }}
    return shellcode
submit:
    return exploit()
```
Actual result

The code assembles successfully without any errors. The assembler resolves the call label instruction to the address of the last definition of label.
This is shown in the resulting disassembly, where the call at offset 0 targets the ret instruction at offset 0x11 (the second label).
```
0:  e8 0c 00 00 00          call   0x11
5:  58                      pop    rax
6:  5b                      pop    rbx
7:  48 33 c3                xor    rax,rbx
a:  48 05 15 00 00 00       add    rax,0x15
10: 50                      push   rax
11: c3                      ret
```

### PR DESCRIPTION
**Pull request by sijung07**
Closes #266

### CODE REVIEW

File: src/Assembly/Intel/Assembler.fs [hunk 1]
```diff
@@ -48,7 +48,11 @@ type Assembler(isa: ISA, baseAddr: Addr) =
 
   let addLabeldef lbl =
     updateUserState (fun us ->
-      { us with LabelMap = Map.add lbl us.CurIndex us.LabelMap })
+     if Map.containsKey lbl us.LabelMap then
+       let eMsg = sprintf "Label '%s' already defined" lbl
```
Comment (sangkilc) [inline src/Assembly/Intel/Assembler.fs]: Use string interpolation than `sprintf`

**Review by gnrkr789 — APPROVED** [review]
